# Generated by Django 5.1.1 on 2026-07-08 19:07

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0078_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='(must be under 1000 characters)', max_length=1000, null=True, validators=[videos.models.validate_characters]),
        ),
    ]
