# Generated by Django 5.1.1 on 2026-07-10 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0079_alter_video_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.FileField(
                blank=True,
                help_text="(must be a png or jpg between 1kb and 10mb. If empty, the first frame of the video will be used)",
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="(must be an mp4 or mov between 1kb and 5gb and be under 2 hours)",
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov"]
                    )
                ],
            ),
        ),
    ]
