name: Bug Report
description: Report a problem with Glomble
labels: ["bug"]
title: "[Bug]: "
body:
  - type: checkboxes
    attributes:
      options:
        - label: I have searched existing issues and am confident that this bug is unique.
  - type: input
    id: description
    attributes:
      label: Description
      description: A clear and concise description (in one line) of what the bug is.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How to Reproduce?
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here. If applicable, add screenshots to help explain your problem.
